dist: trusty

language: php

php:
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
 - '7.2'
 - '7.3'
 - 'nightly'

matrix:
 allow_failures:
  - php: nightly

install:
 - composer install

script:
 - ./vendor/bin/phpunit

notifications:
 email: false
